import { Link, useNavigate } from 'react-router-dom';

export function ItemCustomizePage() {
  const navigate = useNavigate();
  return (
    <div className="sync-alert-layout" style={{ background: '#8e8a86' }}>
      <header className="sync-topbar" style={{ position: 'relative', zIndex: 1, background: '#fff', borderBottom: 0 }}><Link className="link-reset sync-logo" to="/"><span>Sizzle</span></Link></header>
      <div style={{ display: 'flex', justifyContent: 'center', padding: '80px 20px' }}><div className="sync-card" style={{ width: 560, borderRadius: 24, overflow: 'hidden', boxShadow: '0 26px 48px rgba(0,0,0,.22)' }}><div style={{ height: 196, background: '#1f1b19', position: 'relative', display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', padding: '14px 14px 0' }}><span className="sync-pill sync-pill-status" style={{ background: 'var(--accent)', color: '#fff' }}>Popular</span><button onClick={() => navigate(-1)} style={{ width: 34, height: 34, borderRadius: '50%', background: 'rgba(255,255,255,.18)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#fff', fontSize: 22, border: 'none', cursor: 'pointer', padding: 0 }}>×</button><div style={{ position: 'absolute', inset: 0, display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'rgba(255,255,255,.12)', fontSize: 24, letterSpacing: '.28em', fontWeight: 700 }}>TACOS</div></div><div style={{ padding: '26px 28px 28px' }} className="sync-stack"><div className="sync-spread" style={{ alignItems: 'flex-start' }}><div className="sync-row-title" style={{ fontSize: 20 }}>Tacos Al Pastor</div><div style={{ color: 'var(--accent)', fontSize: 20, fontWeight: 800 }}>$9.00</div></div><div className="sync-subtitle" style={{ maxWidth: 'none' }}>Marinated pork, pineapple, onion, cilantro on corn tortillas. Slow-roasted al pastor style with fresh lime.</div><div className="sync-inline-actions"><span className="sync-pill sync-pill-status" style={{ background: '#fff', border: '1px solid #f3c8b5' }}>Spicy</span><span className="sync-pill" style={{ background: '#fff', border: '1px solid var(--border)', color: '#9c9890' }}>Gluten-Free</span></div><label className="auth-field"><span className="sync-label">Special Instructions</span><textarea className="auth-input" style={{ height: 70, padding: 16, resize: 'none' }}>e.g. extra salsa, no onion...</textarea></label><div className="sync-inline-actions"><div className="sync-stepper" style={{ width: 122, height: 42 }}><span>−</span><span>1</span><span>+</span></div><Link className="link-reset sync-button" to="/cart" style={{ flex: 1, justifyContent: 'center', fontSize: 16 }}>Add to Order · $9.00</Link></div></div></div></div>
    </div>
  );
}
