import { Link } from 'react-router-dom';
import { Brand } from '../components/Brand';
import { useAuth } from '../lib/auth';

export function SearchEmptyPage() {
  const { profile, user } = useAuth();
  const initial = profile?.full_name?.charAt(0)?.toUpperCase() || user?.email?.charAt(0)?.toUpperCase() || '?';
  return (
    <div className="sync-page"><header className="sync-topbar"><Brand className="sync-logo" titleClassName="" /><form className="sync-topbar-search"><span>⌕</span><input defaultValue="Mexican street food, Mission..." /></form><div className="sync-topbar-right"><span className="sync-heart">♡</span><div className="sync-avatar">{initial}</div></div></header><main className="sync-content"><div className="sync-spread" style={{ marginBottom: 20, flexWrap: 'wrap' }}><div className="sync-inline-actions"><span className="sync-button-dark" style={{ padding: '10px 16px' }}>Mexican ×</span><span className="sync-button-outline" style={{ padding: '10px 16px' }}>Mission District</span><span className="sync-button-outline" style={{ padding: '10px 16px' }}>Rating 4+</span><span className="sync-button-outline" style={{ padding: '10px 16px' }}>Open Now</span><span className="sync-button-outline" style={{ padding: '10px 16px' }}>More</span></div><span className="sync-muted">0 vendors found</span></div><div className="sync-card sync-outline-block"><div className="sync-center-block"><div className="sync-empty-icon">0</div><h1 className="sync-title" style={{ fontSize: 26 }}>No Vendors Match These Filters</h1><div className="sync-subtitle">Try widening your distance, clearing one filter, or exploring vendors that open later today.</div><div className="sync-inline-actions"><Link className="link-reset sync-button" to="/search">Clear Filters</Link><Link className="link-reset sync-button-outline" to="/map">View Map Instead</Link></div></div><div className="sync-suggestion-grid" style={{ maxWidth: 760, margin: '28px auto 0' }}><div className="sync-suggestion"><div className="sync-label">Suggestion</div><div className="sync-row-title">Remove the distance limit</div><div className="sync-muted">Some top-rated trucks nearby are just outside your current radius.</div></div><div className="sync-suggestion sync-suggestion-dark"><div className="sync-label">Suggestion</div><div className="sync-row-title">Get Notified When Vendors Go Live</div><div className="sync-subtitle" style={{ color: '#cfc7bc', maxWidth: 'none' }}>Save this search and we’ll tell you when new vendors match your area.</div></div></div></div></main></div>
  );
}
