// @ts-nocheck
export const VENDORS = [
  {
    id: 1,
    name: "Marco's Street Tacos",
    cuisine: 'Mexican',
    cuisineLabel: 'Mexican Street Food',
    location: 'Mission District',
    price: '$',
    rating: 4.8,
    reviews: 127,
    distance: '0.3 mi',
    description: 'Tacos, burritos, churros, and more',
    fullDescription: 'Authentic Mexican street tacos made with family recipes. Fresh ingredients, bold flavors, and served with a smile.',
    bgColor: '#1C1917',
    label: 'TACOS',
    open: true,
    closesAt: '9:00 PM',
    featured: true,
    menu: [
      { name: 'Tacos Al Pastor', description: 'Marinated pork, pineapple, onion, cilantro', price: 9.0, popular: true },
      { name: 'Burrito Bowl', description: 'Rice, beans, protein, salsa, guac, sour cream', price: 11.0 },
      { name: 'Churros', description: 'Cinnamon sugar sticks with chocolate sauce', price: 7.0 },
      { name: 'Elote', description: 'Grilled corn with mayo, cotija, chili, lime', price: 6.0 },
      { name: 'Horchata', description: 'Traditional rice milk with cinnamon and vanilla', price: 4.5, soldOut: true },
    ],
    reviewsList: [
      { name: 'Sarah K.', initial: 'S', avatarBg: '#E8E6E1', avatarColor: '#9C9890', stars: 5, text: "Best al pastor tacos I've had outside of Mexico City. The pineapple is perfectly caramelized. Will be back every week!", time: '2 days ago' },
      { name: 'David M.', initial: 'D', avatarBg: '#FFF4EE', avatarColor: '#FF6B2C', stars: 4, text: 'The burrito bowl is massive and packed with flavor. Churros are a must-get dessert. Solid value for the price.', time: '1 week ago' },
      { name: 'Lisa T.', initial: 'L', avatarBg: '#E8E6E1', avatarColor: '#9C9890', stars: 5, text: 'Found this gem on Sizzle. The elote is incredible and churros are addictive. Super friendly staff too.', time: '2 weeks ago' },
    ],
  },
  {
    id: 2,
    name: 'Bao House',
    cuisine: 'Taiwanese',
    cuisineLabel: 'Taiwanese Street Food',
    location: 'SoMa',
    price: '$$',
    rating: 4.9,
    reviews: 203,
    distance: '0.5 mi',
    description: 'Steamed bao buns, dumplings, bubble tea',
    fullDescription: 'Hand-folded bao buns stuffed with slow-braised fillings. Traditional Taiwanese flavors with a modern street food twist.',
    bgColor: '#2C3E2E',
    label: 'BAO',
    open: true,
    closesAt: '10:00 PM',
    featured: true,
    menu: [
      { name: 'Pork Belly Bao', description: 'Braised pork belly, pickled mustard greens, cilantro', price: 8.0, popular: true },
      { name: 'Chicken Bao', description: 'Crispy fried chicken, slaw, spicy mayo', price: 8.0 },
      { name: 'Pork Dumplings (6pc)', description: 'Pan-fried with ginger soy dipping sauce', price: 10.0 },
      { name: 'Scallion Pancake', description: 'Crispy layered flatbread with chili oil', price: 6.5 },
      { name: 'Taro Bubble Tea', description: 'Creamy taro milk tea with tapioca pearls', price: 5.5 },
    ],
    reviewsList: [
      { name: 'Emily R.', initial: 'E', avatarBg: '#E8F5E9', avatarColor: '#2D9F6F', stars: 5, text: 'The pork belly bao is unreal. Melt-in-your-mouth tender with the perfect balance of sweet and savory.', time: '3 days ago' },
      { name: 'James W.', initial: 'J', avatarBg: '#E8E6E1', avatarColor: '#9C9890', stars: 5, text: 'Best bao buns in the city. The dumplings are crispy on the bottom, juicy inside.', time: '5 days ago' },
      { name: 'Mia C.', initial: 'M', avatarBg: '#FFF4EE', avatarColor: '#FF6B2C', stars: 5, text: "Don't sleep on the scallion pancake — it's flaky and addictive.", time: '1 week ago' },
    ],
  },
  {
    id: 3,
    name: 'La Cocina Arepas',
    cuisine: 'Venezuelan',
    cuisineLabel: 'Venezuelan Street Food',
    location: 'Castro',
    price: '$',
    rating: 4.7,
    reviews: 91,
    distance: '0.8 mi',
    description: 'Arepas, empanadas, fresh juices',
    fullDescription: 'Crispy-on-the-outside, fluffy-on-the-inside arepas stuffed with traditional Venezuelan fillings. A taste of home on every corner.',
    bgColor: '#4A3728',
    label: 'AREPAS',
    open: true,
    closesAt: '8:30 PM',
    featured: true,
    menu: [
      { name: 'Reina Pepiada', description: 'Chicken, avocado, mayo — the classic arepa', price: 10.0, popular: true },
      { name: 'Pabellón Arepa', description: 'Shredded beef, black beans, plantain, white cheese', price: 11.0 },
      { name: 'Empanadas (3pc)', description: 'Crispy corn empanadas with beef or cheese', price: 8.5 },
      { name: 'Cachapa', description: 'Sweet corn pancake with queso de mano', price: 9.0 },
      { name: 'Papelón con Limón', description: 'Traditional raw cane sugar lemonade', price: 4.0 },
    ],
    reviewsList: [
      { name: 'Ana P.', initial: 'A', avatarBg: '#FFF4EE', avatarColor: '#FF6B2C', stars: 5, text: 'Authentic arepas. The Reina Pepiada tastes like home.', time: '1 day ago' },
      { name: 'Carlos G.', initial: 'C', avatarBg: '#E8E6E1', avatarColor: '#9C9890', stars: 4, text: 'Solid arepas and empanadas with a perfect crisp.', time: '4 days ago' },
      { name: 'Rachel B.', initial: 'R', avatarBg: '#E8E6E1', avatarColor: '#9C9890', stars: 5, text: 'First time trying Venezuelan food and I am hooked.', time: '2 weeks ago' },
    ],
  },
  {
    id: 4,
    name: "Niko's Greek Cart",
    cuisine: 'Greek',
    cuisineLabel: 'Greek Street Food',
    location: 'Financial District',
    price: '$$',
    rating: 4.6,
    reviews: 78,
    distance: '1.2 mi',
    description: 'Gyros, souvlaki, baklava',
    fullDescription: 'Classic Greek street food made fresh to order. Juicy gyros, crispy falafel, and house-made tzatziki that transports you to Athens.',
    bgColor: '#3D2E42',
    label: 'GYROS',
    open: true,
    closesAt: '7:00 PM',
    menu: [
      { name: 'Lamb Gyro', description: 'Seasoned lamb, tomato, onion, tzatziki in warm pita', price: 12.0, popular: true },
      { name: 'Chicken Souvlaki Plate', description: 'Grilled chicken skewers, rice, salad, pita', price: 14.0 },
      { name: 'Falafel Wrap', description: 'Crispy chickpea falafel, hummus, pickled veg', price: 10.0 },
      { name: 'Greek Salad', description: 'Tomato, cucumber, olives, feta, oregano dressing', price: 8.0 },
      { name: 'Baklava (2pc)', description: 'Flaky phyllo pastry with walnuts and honey syrup', price: 5.0 },
    ],
    reviewsList: [
      { name: 'Tom H.', initial: 'T', avatarBg: '#E8E6E1', avatarColor: '#9C9890', stars: 5, text: 'The lamb gyro is perfectly spiced and the tzatziki is fresh.', time: '3 days ago' },
      { name: 'Priya S.', initial: 'P', avatarBg: '#FFF4EE', avatarColor: '#FF6B2C', stars: 4, text: 'Great falafel wrap — crispy outside, soft inside.', time: '1 week ago' },
      { name: 'Mark L.', initial: 'M', avatarBg: '#E8E6E1', avatarColor: '#9C9890', stars: 5, text: 'The baklava alone is worth the trip. Outstanding.', time: '2 weeks ago' },
    ],
  },
  {
    id: 5,
    name: 'El Fuego Birria',
    cuisine: 'Mexican',
    cuisineLabel: 'Mexican Street Food',
    location: 'Mission District',
    price: '$$',
    rating: 4.9,
    reviews: 89,
    distance: '0.6 mi',
    description: 'Birria tacos, consomme, quesabirria',
    fullDescription: 'Rich, slow-cooked birria served the traditional way. Our consomme is simmered for 12 hours for maximum depth of flavor.',
    bgColor: '#2C3E2E',
    label: 'BIRRIA',
    open: true,
    closesAt: '9:30 PM',
    menu: [
      { name: 'Birria Tacos (3pc)', description: 'Crispy tortillas dipped in consomme, filled with braised beef', price: 13.0, popular: true },
      { name: 'Quesabirria', description: 'Cheese-stuffed birria quesadilla with consomme dip', price: 14.0 },
      { name: 'Birria Ramen', description: 'Ramen noodles in spicy birria broth, topped with beef', price: 15.0 },
      { name: 'Consomme Cup', description: 'Rich beef broth with onion, cilantro, lime', price: 5.0 },
      { name: 'Tres Leches Slice', description: 'Three-milk soaked cake with whipped cream', price: 6.0, soldOut: true },
    ],
    reviewsList: [
      { name: 'Miguel R.', initial: 'M', avatarBg: '#FFF4EE', avatarColor: '#FF6B2C', stars: 5, text: 'The birria tacos are the best in SF. That consomme is liquid gold.', time: '1 day ago' },
      { name: 'Jenny L.', initial: 'J', avatarBg: '#E8E6E1', avatarColor: '#9C9890', stars: 5, text: 'Quesabirria changed my life. The cheese pull is insane.', time: '3 days ago' },
      { name: 'Kevin P.', initial: 'K', avatarBg: '#E8E6E1', avatarColor: '#9C9890', stars: 5, text: 'Birria ramen is genius. The broth is so rich and flavorful.', time: '1 week ago' },
    ],
  },
  {
    id: 6,
    name: 'Doña Rosa Tamales',
    cuisine: 'Mexican',
    cuisineLabel: 'Mexican Street Food',
    location: '24th Street',
    price: '$',
    rating: 4.7,
    reviews: 64,
    distance: '1.1 mi',
    description: 'Handmade tamales, atole, champurrado',
    fullDescription: 'Handmade tamales wrapped in banana leaves, just like Doña Rosa learned from her grandmother in Oaxaca. Each one made with love.',
    bgColor: '#3A2F28',
    label: 'TAMALES',
    open: false,
    closesAt: '6:00 PM',
    menu: [
      { name: 'Pork Tamale', description: 'Slow-cooked pork in red chile sauce, banana leaf wrapped', price: 5.0, popular: true },
      { name: 'Chicken Mole Tamale', description: 'Shredded chicken in rich Oaxacan mole negro', price: 5.5 },
      { name: 'Rajas con Queso Tamale', description: 'Roasted poblano strips with melted Oaxacan cheese', price: 5.0 },
      { name: 'Champurrado', description: 'Warm chocolate corn-based drink with cinnamon', price: 4.0 },
      { name: 'Atole de Fresa', description: 'Strawberry-flavored warm corn drink', price: 3.5 },
    ],
    reviewsList: [
      { name: 'Rosa M.', initial: 'R', avatarBg: '#FFF4EE', avatarColor: '#FF6B2C', stars: 5, text: 'These tamales are the real deal. The masa is fluffy and rich.', time: '2 days ago' },
      { name: 'Diego F.', initial: 'D', avatarBg: '#E8E6E1', avatarColor: '#9C9890', stars: 5, text: 'Chicken mole tamale is outstanding. Pure Oaxaca.', time: '1 week ago' },
      { name: 'Sarah W.', initial: 'S', avatarBg: '#E8E6E1', avatarColor: '#9C9890', stars: 4, text: 'Champurrado on a cold SF morning is everything.', time: '3 weeks ago' },
    ],
  },
  {
    id: 7,
    name: 'Esquina del Elote',
    cuisine: 'Mexican',
    cuisineLabel: 'Mexican Street Snacks',
    location: 'Dolores Park',
    price: '$',
    rating: 4.5,
    reviews: 43,
    distance: '0.4 mi',
    description: 'Elote, esquites, mangonada, fruit cups',
    fullDescription: 'The perfect Dolores Park snack stop. Fresh grilled corn, tangy mangonadas, and colorful fruit cups to enjoy in the sun.',
    bgColor: '#4A3728',
    label: 'ELOTE',
    open: true,
    closesAt: '7:30 PM',
    menu: [
      { name: 'Elote', description: 'Grilled corn on the cob with mayo, cotija, chili, lime', price: 5.0, popular: true },
      { name: 'Esquites', description: 'Corn in a cup with the same elote toppings', price: 5.5 },
      { name: 'Mangonada', description: 'Mango sorbet, chamoy, tajin, tamarind straw', price: 7.0 },
      { name: 'Fruit Cup', description: 'Seasonal fruit with lime, chili, and chamoy', price: 6.0 },
      { name: 'Agua Fresca', description: 'Horchata, jamaica, or tamarindo (16oz)', price: 4.0 },
    ],
    reviewsList: [
      { name: 'Olivia N.', initial: 'O', avatarBg: '#FFF4EE', avatarColor: '#FF6B2C', stars: 5, text: 'Best elote in the park. Perfectly charred and loaded with cotija.', time: '1 day ago' },
      { name: 'Ben L.', initial: 'B', avatarBg: '#E8E6E1', avatarColor: '#9C9890', stars: 4, text: 'Esquites are addictive and the mangonada is a must.', time: '6 days ago' },
      { name: 'Nina P.', initial: 'N', avatarBg: '#E8E6E1', avatarColor: '#9C9890', stars: 4, text: 'Great snacks for Dolores Park. Fast, friendly, and tasty.', time: '2 weeks ago' },
    ],
  },
];

export function getFeaturedVendors() {
  return VENDORS.filter(v => v.featured).slice(0, 3);
}

export function getVendorById(id) {
  const numId = Number(id);
  return VENDORS.find(v => v.id === numId);
}
